### ISSUE TITLE
Type annotations and formatter

### ISSUE THREAD

**Issue by why-not-try-calmer** [openSUSE/defrag-api#9]
I am using Pylance to guide/enforce type annotations (as per Python 3.8.10) and autopep8 as formatter.

1. Do you agree to enforce type annotations at least on function signatures?
2. Do you agree to use Pylance for it?
3. Which formatter do you prefer?

**Comment by muadib** [comment]
I'm OK with 1. and 2.
With that said, I'm in the process of introducing myself to Python, so I'll be setting up Pylance :)

**Comment by why-not-try-calmer** [comment]
> I'm OK with 1. and 2.
> With that said, I'm in the process of introducing myself to Python, so I'll be setting up Pylance :)

Great!

**Comment by KaratekHD** [comment]
I'm actually not really happy with pylance. It would require me to use VS Code for development, which I generally dislike. There once was a plugin for Vim for Pylance, but Microsoft killed it. So if you guys totally want to use it I can life with it, but I'm.not happy with it

**Comment by why-not-try-calmer** [comment]
Pylance (the language server / VSCode extension) uses the Pyright type checker, which is available for Vim. Would that be Ok for you? 

At the end of the day it does not matter which tool you use as long as it applies the same conventions as Pyright, which is I think one of the most up-to-date (https://github.com/microsoft/pyright#type-checking-features) type checker for Python

**Comment by KaratekHD** [comment]
I will look into that, but probably for the reasons stated on Telegram only starting from Thursday the 22nd.

**Comment by why-not-try-calmer** [comment]
Any news on Pylance / Pyright?

As for the formatter, I myself am unhappy with autopep8. The standard is good but concretely it really overdoes things and is not always consistent as far as vertical spacing. Perhaps it's a configuration issue. Will keep you posted.
